### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by chfast** [wasmx/fizzy#644]
- [ ] Add coverage for Rust. #706
- [x] Add GCC coverage for spectests. #649
- [x] Improve LLVM coverage for spectests - do it only for `fizzy-spectests` binary. #646
- [x] Upload spectests coverage to codecov with separate tag. #649
